apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  annotations:
    kubernetes.io/change-cause: "initial deployment mongodb:1.0.0"
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  replicas: 1
  selector:
  # using these labels replica set selects the pod and create replicas for that matched labels pod
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  # This is pod definition, pod is subset of replica set
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: manidevops20/mongodb:1.0.0

---

#service definition
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: db
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017 #service port
    targetPort: 27017  #container port